// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJM5XWS-GKJL1HPvxgHypnFXkv64xIPe0',
    appId: '1:772585005702:web:de53f31316eba840fee707',
    messagingSenderId: '772585005702',
    projectId: 'oshc-australia',
    authDomain: 'oshc-australia.firebaseapp.com',
    storageBucket: 'oshc-australia.appspot.com',
    measurementId: 'G-S0VTXH1W4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbM4th2M673Kl1np_HXjrNvnfl3ObKKZE',
    appId: '1:772585005702:android:85a52644e46041f8fee707',
    messagingSenderId: '772585005702',
    projectId: 'oshc-australia',
    storageBucket: 'oshc-australia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKLvZKduB15q4DZiYe8_99sSCFFUn-lw',
    appId: '1:772585005702:ios:7a5055fda449b16afee707',
    messagingSenderId: '772585005702',
    projectId: 'oshc-australia',
    storageBucket: 'oshc-australia.appspot.com',
    iosClientId: '772585005702-6pffalvtfqvik3dicrdkiujn32lpgpkn.apps.googleusercontent.com',
    iosBundleId: 'com.oshcAustralia.oshcaustralia',
  );
}
